Chem += Chem_computeDt.o \
        Chem_interface.o \
	Chem_init.o \
	Chem.o
        
Chem += Chem_data.o \
	ch_bsimp_step.o \
	ch_bsimp_step_local.o \
	ch_computeEquilibrium.o \
	ch_evolveChemDt.o \
	ch_networkDerivs.o \
	ch_networkDerivsPack.o \
	ch_networkJacobnNumericalPack.o \
	ch_poly_extrap.o \
	ch_setEquilibriumAbundancesHe.o \
	erf_util.o \
	ch_chemRates.o \
	ch_ratesInterp.o \
	ch_thermoRates.o \
	ch_thermoRatesInterp.o \
        ch_calcCoolingRate.o         




